import type { Metadata } from "next";
import "./globals.css";
import Header from "./components/header";
import { Nunito, Inter } from "next/font/google"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

//  Configure PT Sans font
const nunito = Nunito({
  subsets: ["latin"],
  weight: ["400", "700"],
  display: "swap",
  variable: "--font-nunito",
})

//  Configure Playfair Display font
const inter = Inter({
  subsets: ["latin"],
  weight: ["400", "700"],
  display: "swap",
  variable: "--font-inter",
})


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html >
      <body
        className='antialiased bg-dark'
      >
        <Header/>
        {children}
      </body>
    </html>
  );
}
