import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function LoginLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased bg-slate-900`}
      >
        <section className="w-full h-[10vh] bg-dark flex justify-center items-center">
          <Link href={'/'}>
          <Image src='/logos/logo.svg' width={100} height={50} alt="logo"/>
          </Link>
        </section>
        <section className="w-full h-[90vh] flex justify-center items-center">
          {children}
        </section>
      </body>
    </html>
  );
}
